@endpoint=http://localhost:3000

########################## GET ALL CUSTOMER
GET {{endpoint}}/customer

###
########################## GET ONE CUSTOMER
GET {{endpoint}}/customer/1

###
########################## CREATE CUSTOMER
POST {{endpoint}}/customer
Content-Type: application/json

{
  "store_id": 1,
  "first_name": "Batman",
  "last_name": "PasWayne",
  "email": "batmail@mail.fr",
  "address_id": 1,
  "activebool": true,
  "active": 1
}

###
########################## UPDATE CUSTOMER
PATCH {{endpoint}}/customer/601
Content-Type: application/json

{
  "last_name": "PasDuTouTWayne"
}

###
########################## DELETE CUSTOMER
DELETE {{endpoint}}/customer/602


########################## GET ALL FILM
GET {{endpoint}}/film

###
########################## GET ONE FILM
GET {{endpoint}}/film/1

###
########################## CREATE FILM
POST {{endpoint}}/film
Content-Type: application/json

{
  "film_id": 1,
  "title": "ACADEMY TEST",
  "description": "An hepic story about a man who want to become a good developper",
  "release_year": 2024,
  "language_id": 1,
  "original_language_id": null,
  "rental_duration": 6,
  "rental_rate": "0.99",
  "length": 86,
  "replacement_cost": "20.99",
  "rating": "PG",
  "last_update": "2006-02-15T05:03:42.000Z",
  "special_features": [
    "Deleted Scenes",
    "Behind the Scenes"
  ]
}

###
########################## UPDATE CUSTOMER
PATCH {{endpoint}}/film/1
Content-Type: application/json

{
  "film_id": 1,
  "title": "ACADEMY TEST",
  "description": "An hepic story about a man who want to become a good developper",
  "language_id": 1,
  "original_language_id": null,
  "rental_duration": 6,
  "rental_rate": "0.99",
  "length": 86,
  "replacement_cost": "20.99",
  "rating": "PG",
  "last_update": "2006-02-15T05:03:42.000Z",
  "special_features": [
    "Deleted Scenes",
    "Behind the Scenes"
  ]
}

###
########################## DELETE CUSTOMER
DELETE {{endpoint}}/film/602

########################## GET ALL RENTAL (ne pas lancer ça fait buguer) 
GET {{endpoint}}/rental

###
########################## GET ONE RENTAL
GET {{endpoint}}/rental/2

###
########################## CREATE RENTAL
POST {{endpoint}}/rental
Content-Type: application/json

{
  "title": "ACADEMY TEST",
  "rental_id": 1,
  "rental_date": "2005-05-24T22:53:30.000Z",
  "inventory_id": 366,
  "customer_id": 132,
  "return_date": "2005-06-10T22:04:30.000Z",
  "staff_id": 1
}

###
########################## UPDATE RENTAL
PATCH {{endpoint}}/rental/1
Content-Type: application/json

{
  "rental_id": 1,
  "rental_date": "2005-05-24T22:53:30.000Z",
  "inventory_id": 367,
  "customer_id": 130,
  "return_date": "2005-05-26T22:04:30.000Z",
  "staff_id": 1,
  "last_update": "2006-02-15T21:30:53.000Z"
}

###
########################## DELETE RENTAL
DELETE {{endpoint}}/rental/16054