@endpoint=http://localhost:3000

########################## GET ALL CUSTOMER
GET {{endpoint}}/customer

###
########################## GET ONE CUSTOMER
GET {{endpoint}}/customer/1

###
########################## CREATE CUSTOMER
POST {{endpoint}}/customer
Content-Type: application/json

{
  "store_id": 1,
  "first_name": "Batman",
  "last_name": "PasWayne",
  "email": "batmail@mail.fr",
  "address_id": 3,
  "activebool": true,
  "active": 1,
  "timezone": "Europe/Parise"
}

###
########################## UPDATE CUSTOMER
# MODIFIER L'ID USER EN FONCTION DE LA CREATION PRECEDENTE
PATCH {{endpoint}}/customer/627
Content-Type: application/json

{
  "last_name": "PasDuTouTWayne"
}

###
########################## DELETE CUSTOMER
DELETE {{endpoint}}/customer/626


########################## GET ALL FILM
GET {{endpoint}}/film

###
########################## GET ONE FILM
GET {{endpoint}}/film/1


########################## GET ALL RENTAL (ne pas lancer ça fait buguer) 
GET {{endpoint}}/rental

###
########################## GET ONE RENTAL
GET {{endpoint}}/rental/2
 
###
########################## CREATE RENTAL
# CHANGER UTILISATEUR SI ERREUR UNIQUE CONSTRAINT
POST {{endpoint}}/rental
Content-Type: application/json

{
  "title": "AGENT TRUMAN",
  "rental_date": "2024-08-07T00:00:00.000Z",
  "customer_id": 198,
  "return_date": "2024-08-23T00:00:00.000Z",
  "staff_id": 1
}

###
########################## UPDATE RENTAL
# CHANGER UTILISATEUR SI ERREUR UNIQUE CONSTRAINT
PATCH  {{endpoint}}/rental/16073
Content-Type: application/json

{
  "rental_date": "2024-08-11T00:00:00.000Z",
  "customer_id": 196,
  "return_date": "2024-08-24T00:00:00.000Z",
  "staff_id": 1
}
###
########################## GET ALL REMINDER
GET {{endpoint}}/reminder

###
########################## LAUNCH ONE REMINDER
GET {{endpoint}}/reminder/27